USE [master]
GO

/****** Object:  Database [Loymark]    Script Date: 3/11/2022 10:23:12 a. m. ******/
CREATE DATABASE [Loymark]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Loymark', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Loymark.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Loymark_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Loymark_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Loymark].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Loymark] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Loymark] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Loymark] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Loymark] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Loymark] SET ARITHABORT OFF 
GO

ALTER DATABASE [Loymark] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Loymark] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Loymark] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Loymark] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Loymark] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Loymark] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Loymark] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Loymark] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Loymark] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Loymark] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Loymark] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Loymark] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Loymark] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Loymark] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Loymark] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Loymark] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Loymark] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Loymark] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Loymark] SET  MULTI_USER 
GO

ALTER DATABASE [Loymark] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Loymark] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Loymark] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Loymark] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Loymark] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Loymark] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Loymark] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Loymark] SET  READ_WRITE 
GO